[package]
name = "embed"
version = "0.1.0"
edition = "2021"

[dependencies]
embed_anything = "0.6.4"
vectorbase = {path = "../../", version = "0.0.2"}
wwml =  {version ="0.1.1",features = ["cpu"]}
tokio = {version ="1.40.0",features = ["full"]}