[package]
name = "hnsw2"
version = "0.1.0"
edition = "2021"

[dependencies]
hnsw = "0.11.0"
galois = {path = "../../../galois", version = "0.1.0"}
rand = "0.8.5"
space = { version = "0.17.0", default-features = false, features = ["alloc"] }
rand_pcg = { version = "0.3.1", features = ["serde1"] }